import { drizzle } from "drizzle-orm/d1";
import * as schema from "./schema";

// Bindings from wrangler.jsonc; types generated by `npm run cf-typegen`.
export type AppEnv = { Bindings: Env };

export function getDb(env: Env) {
  return drizzle(env.DB, { schema });
}
