import { drizzle } from "drizzle-orm/d1";
import type { SessionUser } from "../auth";
import * as schema from "./schema";

// Bindings from wrangler.jsonc (types generated by `npm run cf-typegen`), plus
// the signed-in user that requireRole() puts on admin requests.
export type AppEnv = { Bindings: Env; Variables: { user: SessionUser } };

export function getDb(env: Env) {
  return drizzle(env.DB, { schema });
}
